# base configuration pulled from:
# https://github.com/dashbitco/broadway/blob/master/.github/workflows/ci.yml

name: Build & Publish

on:
  push:
    tags:
      - "*"

env:
  MIX_ENV: prod

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 27.2.1
          elixir-version: 1.18.2
      - name: Restore Dependency Cache
        uses: actions/cache@v3
        id: cache-deps
        with:
          path: |
            deps
            _build

      - run: mix deps.get
      - run: mix format --check-formatted
      - name: Build & Publish
        run: |
          mix compile
          mix assets.deploy
          mix release
      - name: Zip
        working-directory: _build/prod/rel
        run: zip -r estore.zip estore
      - name: Release Zip
        uses: softprops/action-gh-release@v2
        with:
          make_latest: true
          files: |
            _build/prod/rel/estore.zip
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          tags: ghcr.io/ewoudje/estore:latest
