# base configuration pulled from:
# https://github.com/dashbitco/broadway/blob/master/.github/workflows/ci.yml

name: Build & Publish

on:
  push:
    tags:
      - "*"

env:
  MIX_ENV: prod

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 28
          elixir-version: 1.19
      - name: Restore Dependency Cache
        uses: actions/cache@v3
        id: cache-deps
        with:
          path: |
            deps
            _build

      - run: mix deps.get
      - run: mix format --check-formatted
      - name: Build & Publish
        run: |
          mix compile
          mix assets.deploy
          mix phx.gen.release
          mix release
      - name: Zip
        run: zip estore.zip _build/prod/rel/estore
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          make_latest: true
          files: |
            estore.zip
